#!/usr/bin/env bash

# alias rm="trash" since storage space is
# cheap and mission failure is expensive.
for v in "${@}"; do
  mv -vbf "${v}" ~/.local/share/Trash/files/$(date '+%Y-%d-%m')-$(uuidgen | tail -c 13)_$(echo "${v}" | tr -d '/ ')
done
exit 0
