#!/usr/bin/env bash

# alias rm="trash"
[[ $* == "-r" || $* == "-rf" || $* == "-fr" ]] && rm -rfv "${@:2}"
[[ $* == "" || $* != "-r" || $* != "-rf" || $* != "-fr" ]] && if mv -vbf "${@}" ~/.local/share/Trash/files/"$(date '+%Y-%d-%m')-$(uuidgen | tail -c 13)_${@}"; then exit 0; fi
